CREATE TABLE IF NOT EXISTS clinics (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON clinics (name);

CREATE TABLE IF NOT EXISTS users (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username   TEXT UNIQUE,
  password   TEXT,
  clinic_id  INT,
  role       TEXT,
  enabled    BOOLEAN DEFAULT TRUE
);
CREATE INDEX ON users (username);
CREATE INDEX ON users (clinic_id);

CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  clinic_id  INT
);
CREATE INDEX ON vets (last_name);
CREATE INDEX ON vets (clinic_id);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT,
  clinic_id  INT
);
CREATE INDEX ON owners (last_name);
CREATE INDEX ON owners (clinic_id);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id) ON DELETE CASCADE,
  clinic_id  INT
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);
CREATE INDEX ON pets (clinic_id);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id) ON DELETE CASCADE,
  visit_date  DATE,
  description TEXT,
  clinic_id   INT
);
CREATE INDEX ON visits (pet_id);
CREATE INDEX ON visits (clinic_id);
